# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# a = firstTerm
# b = secondTerm
# c = thirdTerm

def sequence():     
    a = 1
    b = 2
    c = 0
    sum = 0
    while True:
        c = a + b
        a = c + b
        b = a + c
        if a < 4000000 and a % 2 == 0:
            sum = sum + a
        if b < 4000000 and b % 2 == 0:
            sum = sum + b
        if c < 4000000 and c % 2 == 0:
            sum = sum + c
        if a >= 4000000 or b >= 4000000 or c >= 4000000:
            break
    return sum + 2


print(sequence())
    